In [8]:
import numpy as np

In [9]:
n= int(input("Enter no. of terms: "))
l=[]
for i in range(n):
    l.append(int(input("Enter n numbers: ")))

In [10]:
l

[1, 3, 2, 5, 6, 3]

In [11]:
arr=np.array(l)

In [12]:
arr

array([1, 3, 2, 5, 6, 3])

In [13]:
arr[::-1]

array([3, 6, 5, 2, 3, 1])

In [14]:
print(arr[::-1])

[3 6 5 2 3 1]
